server:
  port: 8120
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
spring:
  application:
    name: common-service
  ## 开发/测试/生产环境分别对应dev/test/prod，可以自由定义
  profiles:
    active: dev



