eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
server:
  port: 8130
spring:
  application:
    name: service-zuul
  ## 开发/测试/生产环境分别对应dev/test/prod，可以自由定义
  profiles:
    active: dev

zuul:
  routes:
    api-a:
      path: /UAffairs/**
      serviceId: common-service
#    api-b:
#      path: /api-b/**
#      serviceId: service-feign