eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
server:
  port: 8130
spring:
  application:
    name: service-zuul

zuul:
  routes:
    api-a:
      path: /knowbox/**
      serviceId: common-service
#    api-b:
#      path: /api-b/**
#      serviceId: service-feign