server:
  port: 8110
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
  hystrix:
    timeoutInMilliseconds: 60000

spring:
  application:
    name: hbase-client
  data:
    hbase:
      quorum: uhadoop-5x2bt3-master1,uhadoop-5x2bt3-master2,uhadoop-5x2bt3-core1
      rootDir: hdfs://Ucluster/hbase
      nodeParent: /hbase
