server:
  port: 8110
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
  hystrix:
    timeoutInMilliseconds: 60000

spring:
  application:
    name: hbase-client
  ## 开发/测试/生产环境分别对应dev/test/prod，可以自由定义
  profiles:
    active: dev
  data:
    hbase:
      quorum: master,slave1
      rootDir: hdfs://master:8020/hbase
      nodeParent: /hbase
